import type { Metadata } from "next";
import { Alexandria, Anybody } from "next/font/google";
import "./globals.css";

const AlexandriaFont = Alexandria({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const AnybodyFont = Anybody({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${AlexandriaFont.variable} ${AnybodyFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
